# Generated by Django 4.0.3 on 2022-04-06 12:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, default='')),
            ],
        ),
        migrations.CreateModel(
            name='Tour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True, default='')),
                ('price', models.IntegerField()),
                ('date', models.DateField()),
                ('days', models.PositiveSmallIntegerField()),
                ('travel_agency', models.CharField(default=None, max_length=100, null=True)),
                ('phone_number', models.CharField(max_length=15)),
                ('phone_number_2', models.CharField(default=None, max_length=15, null=True)),
                ('telegram', models.CharField(max_length=32)),
                ('delete_time', models.DateTimeField(default=None, null=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tours', to='locations.country')),
                ('from_city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tours', to='locations.city')),
                ('services', models.ManyToManyField(related_name='tours', to='tours.service')),
            ],
        ),
    ]
