# Generated by Django 4.0.3 on 2022-04-07 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0002_alter_tour_telegram'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='phone_number_2',
            field=models.CharField(blank=True, default='', max_length=15),
        ),
        migrations.AlterField(
            model_name='tour',
            name='travel_agency',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
