# Generated by Django 4.0.3 on 2022-04-11 07:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TGUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tg_id', models.IntegerField()),
                ('username', models.CharField(blank=True, default='', max_length=64, null=True)),
                ('name', models.CharField(blank=True, default='', max_length=64, null=True)),
                ('lastname', models.CharField(blank=True, default='', max_length=64, null=True)),
                ('phone_number', models.CharField(blank=True, default='', max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='TGPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.SmallIntegerField()),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='locations.country')),
                ('from_city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='locations.city')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tg.tguser')),
            ],
        ),
    ]
